apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-service-x-to-service-y
  namespace: hyperservice  
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: service-y_hyperservice_svc_3000 
  from:
    - targetRef:
        kind: MeshSubset
        tags:
          kuma.io/service: service-x_hyperservice_svc_3000  
      default:
        action: Allow 