apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  name: metrics-default
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  default:
    sidecar:
      profiles:
        appendProfiles:
        - name: None
        include:
        - type: Regex
          match: .*
    backends:
    - type: Prometheus
      prometheus:
        port: 5676
        path: "/metrics"
        tls:
          mode: "Disabled"
    applications:
      - path: "/"
        port: 9103
